// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v4.25.2
// source: examples/wasi/cat/cat.proto

package cat

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *FileCatRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FileCatRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type FileCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FileCatReply) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FileCatReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// go:plugin type=plugin
type FileCat interface {
	Cat(context.Context, *FileCatRequest) (*FileCatReply, error)
}
