//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: tests/import/proto/bar/bar.proto

package bar

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const BarPluginAPIVersion = 1

//go:wasmexport bar_api_version
func _bar_api_version() uint64 {
	return BarPluginAPIVersion
}

var bar Bar

func RegisterBar(p Bar) {
	bar = p
}

//go:wasmexport bar_hello
func _bar_hello(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Request)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := bar.Hello(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
