//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.12
// source: examples/known-types/known/known.proto

package known

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const WellKnownPluginAPIVersion = 1

//export well_known_api_version
func _well_known_api_version() uint64 {
	return WellKnownPluginAPIVersion
}

var wellKnown WellKnown

func RegisterWellKnown(p WellKnown) {
	wellKnown = p
}

//export well_known_diff
func _well_known_diff(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req DiffRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := wellKnown.Diff(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
