//go:build !tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.0.1
// 	protoc               v3.21.5
// source: test/fields/proto/fields.proto

package proto

import (
	context "context"
	errors "errors"
	fmt "fmt"
	wazero "github.com/tetratelabs/wazero"
	api "github.com/tetratelabs/wazero/api"
	sys "github.com/tetratelabs/wazero/sys"
	wasi_snapshot_preview1 "github.com/tetratelabs/wazero/wasi_snapshot_preview1"
	os "os"
)

var _hostFunctions EmptyHostFunctions

func RegisterHostFunctions(h EmptyHostFunctions) {
	_hostFunctions = h
}

func readMemory(ctx context.Context, m api.Module, offset, size uint32) ([]byte, error) {
	buf, ok := m.Memory().Read(ctx, offset, size)
	if !ok {
		return nil, fmt.Errorf("Memory.Read(%d, %d) out of range", offset, size)
	}
	return buf, nil
}

func writeMemory(ctx context.Context, m api.Module, data []byte) (uint64, error) {
	malloc := m.ExportedFunction("malloc")
	if malloc == nil {
		return 0, errors.New("malloc is not exported")
	}
	results, err := malloc.Call(ctx, uint64(len(data)))
	if err != nil {
		return 0, err
	}
	dataPtr := results[0]

	// The pointer is a linear memory offset, which is where we write the name.
	if !m.Memory().Write(ctx, uint32(dataPtr), data) {
		return 0, fmt.Errorf("Memory.Write(%d, %d) out of range of memory size %d",
			dataPtr, len(data), m.Memory().Size(ctx))
	}

	return dataPtr, nil
}

func hostFunctions() map[string]interface{} {
	if _hostFunctions == nil {
		return nil
	}
	return map[string]interface{}{}
}

type FieldTestPlugin struct {
	runtime wazero.Runtime
	config  wazero.ModuleConfig
}

func NewFieldTestPlugin() (*FieldTestPlugin, error) {
	// Choose the context to use for function calls.
	ctx := context.Background()

	// Create a new WebAssembly Runtime.
	r := wazero.NewRuntimeWithConfig(ctx, wazero.NewRuntimeConfig().
		// WebAssembly 2.0 allows use of any version of TinyGo, including 0.24+.
		WithWasmCore2())

	// Combine the above into our baseline config, overriding defaults.
	config := wazero.NewModuleConfig().
		// By default, I/O streams are discarded and there's no file system.
		WithStdout(os.Stdout).WithStderr(os.Stderr)

	return &FieldTestPlugin{
		runtime: r,
		config:  config,
	}, nil
}
func (p *FieldTestPlugin) Load(ctx context.Context, pluginPath string) (FieldTest, error) {
	b, err := os.ReadFile(pluginPath)
	if err != nil {
		return nil, err
	}

	// Create an empty namespace so that multiple modules will not conflict
	ns := p.runtime.NewNamespace(ctx)

	// Instantiate a Go-defined module named "env" that exports functions.
	_, err = p.runtime.NewModuleBuilder("env").
		ExportFunctions(hostFunctions()).
		Instantiate(ctx, ns)
	if err != nil {
		return nil, err
	}

	if _, err = wasi_snapshot_preview1.NewBuilder(p.runtime).Instantiate(ctx, ns); err != nil {
		return nil, err
	}

	// Compile the WebAssembly module using the default configuration.
	code, err := p.runtime.CompileModule(ctx, b, wazero.NewCompileConfig())
	if err != nil {
		return nil, err
	}

	// InstantiateModule runs the "_start" function, WASI's "main".
	module, err := ns.InstantiateModule(ctx, code, p.config)
	if err != nil {
		// Note: Most compilers do not exit the module after running "_start",
		// unless there was an Error. This allows you to call exported functions.
		if exitErr, ok := err.(*sys.ExitError); ok && exitErr.ExitCode() != 0 {
			return nil, fmt.Errorf("unexpected exit_code: %d", exitErr.ExitCode())
		} else if !ok {
			return nil, err
		}
	}

	test := module.ExportedFunction("field_test_test")
	if test == nil {
		return nil, errors.New("field_test_test is not exported")
	}

	malloc := module.ExportedFunction("malloc")
	if malloc == nil {
		return nil, errors.New("malloc is not exported")
	}

	free := module.ExportedFunction("free")
	if free == nil {
		return nil, errors.New("free is not exported")
	}
	return &fieldTestPlugin{module: module,
		malloc: malloc,
		free:   free,
		test:   test,
	}, nil
}

type fieldTestPlugin struct {
	module api.Module
	malloc api.Function
	free   api.Function
	test   api.Function
}

func (p *fieldTestPlugin) Test(ctx context.Context, request Request) (response Response, err error) {
	data, err := request.MarshalVT()
	if err != nil {
		return response, err
	}
	dataSize := uint64(len(data))
	results, err := p.malloc.Call(ctx, dataSize)
	if err != nil {
		return response, err
	}

	dataPtr := results[0]
	// This pointer is managed by TinyGo, but TinyGo is unaware of external usage.
	// So, we have to free it when finished
	defer p.free.Call(ctx, dataPtr)

	// The pointer is a linear memory offset, which is where we write the name.
	if !p.module.Memory().Write(ctx, uint32(dataPtr), data) {
		return response, fmt.Errorf("Memory.Write(%d, %d) out of range of memory size %d", dataPtr, dataSize, p.module.Memory().Size(ctx))
	}
	ptrSize, err := p.test.Call(ctx, dataPtr, dataSize)
	if err != nil {
		return response, err
	}

	// Note: This pointer is still owned by TinyGo, so don't try to free it!
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])

	// The pointer is a linear memory offset, which is where we write the name.
	bytes, ok := p.module.Memory().Read(ctx, resPtr, resSize)
	if !ok {
		return response, fmt.Errorf("Memory.Read(%d, %d) out of range of memory size %d",
			resPtr, resSize, p.module.Memory().Size(ctx))
	}

	if err = response.UnmarshalVT(bytes); err != nil {
		return response, err
	}

	return response, nil
}
