//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.0.1
// 	protoc               v3.21.5
// source: test/fields/proto/fields.proto

package proto

import (
	context "context"
	reflect "reflect"
	unsafe "unsafe"
)

var fieldTest FieldTest

func RegisterFieldTest(p FieldTest) {
	fieldTest = p
}

func ptrToByte(ptr, size uint32) []byte {
	var b []byte
	s := (*reflect.SliceHeader)(unsafe.Pointer(&b))
	s.Len = uintptr(size)
	s.Cap = uintptr(size)
	s.Data = uintptr(ptr)
	return b
}

func byteToPtr(buf []byte) (uint32, uint32) {
	ptr := &buf[0]
	unsafePtr := uintptr(unsafe.Pointer(ptr))
	return uint32(unsafePtr), uint32(len(buf))
}

//export field_test_test
func _field_test_test(ptr, size uint32) uint64 {
	b := ptrToByte(ptr, size)
	var req Request
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := fieldTest.Test(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = byteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

type emptyHostFunctions struct{}

func NewEmptyHostFunctions() EmptyHostFunctions {
	return emptyHostFunctions{}
}
