//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: tests/import/proto/foo/foo.proto

package foo

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const FooPluginAPIVersion = 1

//go:wasmexport foo_api_version
func _foo_api_version() uint64 {
	return FooPluginAPIVersion
}

var foo Foo

func RegisterFoo(p Foo) {
	foo = p
}

//go:wasmexport foo_hello
func _foo_hello(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Request)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := foo.Hello(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
