name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'imgs/**'
      - 'LICENSE'
  pull_request:
env:
  PROTOC_VERSION: "21.12"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'go mod tidy' and push it"
            exit 1
          fi

      - name: Install protoc
        run: |
          wget $PB_REL/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local/bin/
        env:
          PB_REL: https://github.com/protocolbuffers/protobuf/releases

      - name: Run unit tests
        run: make test